### ISSUE TITLE
Just completely whitescreen error-ing out on a conversation

### ISSUE THREAD

**Issue by bnvk** [indieweb/indiewebify-me#22]
The following URL which validates h-entry just fine

http://indiewebify.me/validate-h-entry/?url=https%3A%2F%2Fbrennannovak.com%2Fnotes%2F412

But when sending a webmention with IndieWebify me it fails with a blank white screen

http://indiewebify.me/send-webmentions/?url=https%3A%2F%2Fbrennannovak.com%2Fnotes%2F412

**Comment by snarfed** [comment]
friendly ping, @ShaneHudson noticed just now this is still broken.

**Comment by snarfed** [comment]
cc @aaronpk and @bear since they're making noises about reviving this project. this bug is particularly noticeable.

my first guess was a client side ssl issue, but the same symptom (hang and then timeout) happens on http-only sites, e.g. http://indiewebify.me/send-webmentions/?url=http%3A%2F%2Ftantek.com%2F

**Comment by bear** [comment]
what is needed to get me access to where this is deployed? If it's running PHP 5.3 then the first thing we need to do is upgrade that.

**Comment by aaronpk** [comment]
@barnabywalters @bnvk we'd be happy to move this over to something like Google App Engine (which can host it for free) and then set up automatic deploys from the repo. I'm happy to take over domain registration (from IWC sponsorship funds) if you'd like as well.

**Comment by snarfed** [comment]
yay! btw @aaronpk you can go ahead and set up the app engine project and switch DNS afterward. indiewebify.appspot.com is even available!

**Comment by barnabywalters** [comment]
@aaronpk please feel free to go ahead and set this up on App Engine! You’ll have to bug @bnvk about the domain registration, I didn’t have anything to do with that (one of the reasons I was never able to quickly work on the project).

**Comment by aaronpk** [comment]
Thanks @barnabywalters! Hopefully @bnvk sees this soon! I have it almost ready to roll on App Engine. It will be deployed automatically whenever this repo is updated.

**Comment by bnvk** [comment]
@barnabywalters @aaronpk @bear @snarfed yo, sorry for late to the thread. I'm happy to let you move this over or what have you, as well as sponsorship for the domain. You can either pay me and I'll just let it autorenew or you can take it over :) 

- Just tell me where to point the DNS records
- What registrar / account to transfer to if you want to take that part over as well

**Comment by aaronpk** [comment]
Thanks @bnvk! Probably easiest if I add it to my collection of other indieweb domain names. If it's on namecheap, you can transfer it to "aaronpk" there with this process: https://www.namecheap.com/support/knowledgebase/article.aspx/325/46/how-can-i-push-a-domain-from-one-account-to-another

**Comment by bnvk** [comment]
@aaronpk ok, i've put through the request to transfer the domain! Lemme know once it goes through correctly and such :)

**Comment by aaronpk** [comment]
@bnvk got it, thanks! Now I just have to finish figuring out how to deploy it on app engine!

**Comment by aaronpk** [comment]
This is fixed now! also it's running on app engine and deployed automatically for anything pushed to master!

**Comment by snarfed** [comment]
yay thanks for working on this @aaronpk!

it still hangs for me though, just fyi, at least on sites that accept webmentions, e.g. https://snarfed.org/about and http://tantek.com/ (a check that it's not ssl).

**Comment by aaronpk** [comment]
Well that explains why I just got a webmention from tantek.com! If it's hanging, it's a totally different error and we should open that separately.
